services:
  db:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: HarishSathiya@07
      MYSQL_USER: Harish
      MYSQL_DATABASE: userinfo
      MYSQL_PASSWORD: HarishSathiya@07
    container_name: skillsprint-db-1
    networks:
      - skillsprint-network
    ports:
      - "3307:3306"
    volumes:
      - dbvol:/var/lib/mysql 
  app:
    build:
      context: .
    image: skillsprint:v1
    networks:
      - skillsprint-network
    container_name: skillsprint-app-1
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
volumes:
  dbvol:

networks:
  skillsprint-network:
    driver: bridge