services:
  db:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: HarishSathiya@07
      MYSQL_USER: Harish
      MYSQL_DATABASE: userinfo
      MYSQL_PASSWORD: HarishSathiya@07
    container_name: skillsprint-db-1
    networks:
      - skillsprint-network
    ports:
      - "3307:3306"
    volumes:
      - dbvol:/var/lib/mysql 
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
  app1:
    image: harishss07/skillsprint:v2
    networks:
      - skillsprint-network
    container_name: app1
    environment:
      SERVER_PORT: 3001
      TZ: Asia/Kolkata
    depends_on:
      - db
      - redis
    restart: always
    expose:
      - "3001"
  app2:
    image: harishss07/skillsprint:v2
    container_name: app2
    networks:
      - skillsprint-network
    depends_on:
      - db
      - redis
    restart: always
    environment:
      SERVER_PORT: 3002
      TZ: Asia/Kolkata
    expose:
      - "3002"
  app3:
    image: harishss07/skillsprint:v2
    container_name: app3
    networks:
      - skillsprint-network
    depends_on:
      - db
      - redis
    restart: always
    environment:
      SERVER_PORT: 3003
      TZ: Asia/Kolkata
    expose:
      - "3003"
  redis:
    image: redis:8
    container_name: skillsprint-redis-1
    environment:
      REDIS_PASSWORD: HarishSathiya@07
    command: ["redis-server", "--requirepass", "HarishSathiya@07"]
    networks:
      - skillsprint-network
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

      - ./nginx_certs:/nginx_certs
      - ./frontend:/frontend/www/static
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - skillsprint-network
volumes:
  dbvol:

networks:
  skillsprint-network:
    driver: bridge